// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Server from "next/server";

var redirectMap = [
  [
    "/gdc/aicontest",
    "/gdc/contest/aicontest"
  ],
  [
    "/gdc/dscontest",
    "/gdc/contest/dscontest"
  ],
  [
    "/gdc/workshop/bluefriday",
    "/404"
  ]
];

async function handler(request) {
  var baseUrl = request.url;
  var pathname = request.nextUrl.pathname;
  var redirect = redirectMap.find(function (v) {
        return pathname.startsWith(v[0]);
      });
  if (redirect !== undefined) {
    return Caml_option.some(Server.NextResponse.redirect(new URL(redirect[1], baseUrl)));
  }
  
}

var config = {
  matcher: redirectMap.map(function (v) {
        return v[0];
      })
};

var middleware = {
  handler: handler,
  config: config
};

export {
  middleware ,
}
/* config Not a pure module */
