// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../components/Meta.res.mjs";
import * as Utils from "../../utils/Utils.res.mjs";
import * as GDCUtils from "../../utils/GDCUtils.res.mjs";
import * as ActionBox from "../../components/ActionBox.res.mjs";
import * as EventInfo from "../../utils/EventInfo.res.mjs";
import Link from "next/link";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function GDCIndex$GDCPageCard(props) {
  var extraText = props.extraText;
  var href = props.href;
  var image = props.image;
  var eventType = props.eventType;
  var title = props.title;
  var themeClass = GDCUtils.getClassForTheme(props.theme);
  var tmp;
  if (eventType !== undefined) {
    var match = EventInfo.getEventImage(eventType);
    tmp = JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("img", {
                className: "icon w-4/5 h-4/5",
                alt: match[1],
                src: "/static/img/" + match[0]
              }),
          className: "bg-background absolute top-[8px] right-[8px] w-16 aspect-square flex justify-center items-center rounded-full"
        });
  } else {
    tmp = JsxRuntime.jsx("div", {});
  }
  return Utils.conditionalWrapper((function (children) {
                var className = "w-full " + themeClass + " flex flex-col";
                if (href !== undefined) {
                  return JsxRuntime.jsx(Link, {
                              href: href,
                              className: className,
                              children: children
                            });
                } else {
                  return JsxRuntime.jsx("div", {
                              children: children,
                              className: className
                            });
                }
              }), JsxRuntime.jsxs(JsxRuntime.Fragment, {
                  children: [
                    JsxRuntime.jsxs("div", {
                          children: [
                            image !== undefined ? JsxRuntime.jsx("img", {
                                    className: "w-full h-36 absolute object-cover " + Core__Option.getOr(props.objectAlignment, ""),
                                    alt: title + " cover",
                                    src: image
                                  }) : JsxRuntime.jsx("div", {}),
                            tmp,
                            extraText !== undefined ? JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("img", {
                                                  className: "h-full w-[672px] absolute object-cover object-left",
                                                  src: "/static/img/gdc-band.svg"
                                                }),
                                            JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx("h3", {
                                                        children: extraText,
                                                        className: "absolute"
                                                      }),
                                                  className: "absolute w-full h-full flex justify-start items-center px-4"
                                                })
                                          ],
                                          className: "h-full w-full relative"
                                        }),
                                    className: "h-8 w-full absolute -bottom-1"
                                  }) : JsxRuntime.jsx("div", {})
                          ],
                          className: "relative w-full h-36 "
                        }),
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("h1", {
                                          children: title,
                                          className: "text-[32px]"
                                        }),
                                    JsxRuntime.jsx("h2", {
                                          children: props.subtitle,
                                          className: "text-[16px]"
                                        })
                                  ],
                                  className: "flex flex-col p-4 flex-1 justify-center items-start h-full"
                                }),
                            href !== undefined ? JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("img", {
                                          className: "icon w-full aspect-square",
                                          src: "/static/img/next.svg"
                                        }),
                                    className: "flex justify-center items-center h-full max-w-8 mx-4 content-stretch"
                                  }) : JsxRuntime.jsx("div", {})
                          ],
                          className: "flex bg-background text-foreground h-full items-center"
                        })
                  ]
                }));
}

function GDCIndex$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "Arkimastria GDC9.0",
                      description: "Homepage per l'evento annuale GDC di Arkimastria a.s.a.p.d!",
                      ogImage: "/static/img/gdc/GDC9.0_TitleCard.webp"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            className: "w-full max-w-[504px]",
                            alt: "Illustrazione #RoadToGDC9",
                            src: "/static/img/gdc-ill.svg"
                          }),
                      className: "header w-full px-6 py-12 flex justify-center items-center"
                    }),
                JsxRuntime.jsx(ActionBox.make, {
                      title: "SCARICA IL PROGRAMMA",
                      description: "È stato pubblicato il programma definitivo con la descrizione di giornate, eventi, ospiti, concetti e molto altro! Dagli un’occhiata!!!",
                      href: "https://drive.google.com/uc?export=download&id=1ADDRXCkbZ7bo8P8gnCNPVnFFsYNbrTex",
                      boxType: "Download",
                      shouldFloat: false
                    }),
                JsxRuntime.jsx("div", {
                      className: "h-2"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(GDCIndex$GDCPageCard, {
                              title: "Ebanisteria Meccanica",
                              subtitle: "Free workshop Design Spartano",
                              theme: "Pink",
                              eventType: "Workshop",
                              image: "/static/img/gdc/GDC9.0_DSWorkshop_Cover.webp",
                              href: "/gdc/workshop/dsworkshop",
                              objectAlignment: "object-top"
                            }),
                        JsxRuntime.jsx(GDCIndex$GDCPageCard, {
                              title: "Linografia",
                              subtitle: "Free workshop",
                              theme: "Yellow",
                              eventType: "Workshop",
                              image: "/static/img/gdc/GDC9.0_LinoCutPrint_Cover.webp",
                              href: "/gdc/workshop/linocutprint"
                            }),
                        JsxRuntime.jsx(GDCIndex$GDCPageCard, {
                              title: "BlueFriday",
                              subtitle: "Free workshop cianotipia",
                              theme: "Cyan",
                              eventType: "Workshop",
                              image: "/static/img/gdc/GDC9.0_BlueFriday_Cover.webp",
                              href: "/gdc/workshop/bluefriday",
                              objectAlignment: "object-bottom"
                            }),
                        JsxRuntime.jsx(GDCIndex$GDCPageCard, {
                              title: "Ai Contest",
                              subtitle: "Architettura EFFIMERA",
                              theme: "Orange",
                              eventType: "Contest",
                              image: "/static/img/gdc/GDC9.0_AI_Contest_Cover.webp",
                              href: "/gdc/contest/aicontest"
                            }),
                        JsxRuntime.jsx(GDCIndex$GDCPageCard, {
                              title: "DS Contest",
                              subtitle: "Una tavola, Uno sgabello",
                              theme: "Pink",
                              eventType: "Contest",
                              image: "/static/img/gdc/GDC9.0_DS_Contest_Cover.webp",
                              href: "/gdc/contest/dscontest",
                              extraText: "COMPLETATO!"
                            })
                      ],
                      className: "flex flex-col gap-2 pb-32"
                    })
              ]
            });
}

var $$default = GDCIndex$default;

export {
  $$default as default,
}
/* Meta Not a pure module */
