// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../components/Meta.res.mjs";
import * as Utils from "../../utils/Utils.res.mjs";
import * as GDCUtils from "../../utils/GDCUtils.res.mjs";
import * as EventInfo from "../../utils/EventInfo.res.mjs";
import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function GDCIndex$GDCPageCard(props) {
  var href = props.href;
  var image = props.image;
  var eventType = props.eventType;
  var title = props.title;
  var themeClass = GDCUtils.getClassForTheme(props.theme);
  var tmp;
  if (eventType !== undefined) {
    var match = EventInfo.getEventImage(eventType);
    tmp = JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx("img", {
                className: "icon w-4/5 h-4/5",
                alt: match[1],
                src: "/static/img/" + match[0]
              }),
          className: "bg-background absolute top-[8px] right-[8px] w-16 aspect-square flex justify-center items-center rounded-full"
        });
  } else {
    tmp = JsxRuntime.jsx("div", {});
  }
  return Utils.conditionalWrapper((function (children) {
                var className = "w-full " + themeClass + " flex flex-col";
                if (href !== undefined) {
                  return JsxRuntime.jsx(Link, {
                              href: href,
                              className: className,
                              children: children
                            });
                } else {
                  return JsxRuntime.jsx("div", {
                              children: children,
                              className: className
                            });
                }
              }), JsxRuntime.jsxs(JsxRuntime.Fragment, {
                  children: [
                    JsxRuntime.jsxs("div", {
                          children: [
                            image !== undefined ? JsxRuntime.jsx("img", {
                                    className: "w-full h-36 object-cover",
                                    alt: title + " cover",
                                    src: image
                                  }) : JsxRuntime.jsx("div", {}),
                            tmp
                          ],
                          className: "relative"
                        }),
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("h1", {
                                          children: title,
                                          className: "text-[32px]"
                                        }),
                                    JsxRuntime.jsx("h2", {
                                          children: props.subtitle,
                                          className: "text-[16px]"
                                        })
                                  ],
                                  className: "flex flex-col p-4 flex-1 justify-center items-start h-full"
                                }),
                            href !== undefined ? JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("img", {
                                          className: "icon w-full aspect-square",
                                          src: "/static/img/next.svg"
                                        }),
                                    className: "flex justify-center items-center h-full max-w-8 mx-4 content-stretch"
                                  }) : JsxRuntime.jsx("div", {})
                          ],
                          className: "flex bg-background text-foreground h-full items-center"
                        })
                  ]
                }));
}

function GDCIndex$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "Arkimastria GDC9.0",
                      description: "Homepage per l'evento annuale GDC di Arkimastria a.s.a.p.d!",
                      ogImage: "/static/img/gdc/GDC9.0_TitleCard.webp"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            className: "w-full max-w-[504px]",
                            alt: "Illustrazione #RoadToGDC9",
                            src: "/static/img/gdc-ill.svg"
                          }),
                      className: "header w-full px-6 py-12 flex justify-center items-center"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(GDCIndex$GDCPageCard, {
                              title: "Ai Contest",
                              subtitle: "Architettura EFFIMERA",
                              theme: "Orange",
                              eventType: "Contest",
                              image: "/static/img/gdc/GDC9.0_AI_Contest_Cover.webp",
                              href: "/gdc/aicontest"
                            }),
                        JsxRuntime.jsx(GDCIndex$GDCPageCard, {
                              title: "DS Contest",
                              subtitle: "Una tavola, Uno sgabello",
                              theme: "Pink",
                              eventType: "Contest",
                              image: "/static/img/gdc/GDC9.0_DS_Contest_Cover.webp",
                              href: "/gdc/dscontest"
                            })
                      ],
                      className: "flex flex-col gap-2 pb-32"
                    })
              ]
            });
}

var $$default = GDCIndex$default;

export {
  $$default as default,
}
/* Meta Not a pure module */
