// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Webapi__Url from "rescript-webapi/src/Webapi/Webapi__Url.res.mjs";
import * as Webapi__Fetch from "rescript-webapi/src/Webapi/Webapi__Fetch.res.mjs";

var Req = {};

var Res = {};

var GetServerSideProps = {
  Req: Req,
  Res: Res
};

var GetStaticProps = {};

var GetStaticPaths = {};

var Cookies = {};

var NextUrl = Webapi__Url;

var Request_method_ = Webapi__Fetch.$$Request.method_;

var Request_destination = Webapi__Fetch.$$Request.destination;

var Request_referrerPolicy = Webapi__Fetch.$$Request.referrerPolicy;

var Request_mode = Webapi__Fetch.$$Request.mode;

var Request_credentials = Webapi__Fetch.$$Request.credentials;

var Request_cache = Webapi__Fetch.$$Request.cache;

var Request_redirect = Webapi__Fetch.$$Request.redirect;

var $$Request = {
  method_: Request_method_,
  destination: Request_destination,
  referrerPolicy: Request_referrerPolicy,
  mode: Request_mode,
  credentials: Request_credentials,
  cache: Request_cache,
  redirect: Request_redirect
};

var $$Response = {};

var Link = {};

var Events = {};

var Router = {
  Events: Events
};

var Head = {};

var $$Error = {};

var Dynamic = {};

export {
  GetServerSideProps ,
  GetStaticProps ,
  GetStaticPaths ,
  Cookies ,
  NextUrl ,
  $$Request ,
  $$Response ,
  Link ,
  Router ,
  Head ,
  $$Error ,
  Dynamic ,
}
/* No side effect */
