// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../../components/Meta.res.mjs";
import * as Utils from "../../../utils/Utils.res.mjs";
import * as FloatBox from "../../../components/FloatBox.res.mjs";
import * as Template from "../../../utils/Template.res.mjs";
import * as ArticleHeader from "../../../components/ArticleHeader.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var contents = Template.template([
      "\r\n\r\n  Arkimastria, in occasione della Giornata del Colore 9.0, lancia la seconda edizione del Arkificial Intelligence Contest, un concorso di idee per l'architettura, realizzate attraverso l'uso dei software di intelligenza artificiale generativa.\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  Il ",
      " scelto per la GDC di quest'anno ",
      " riassunto nel titolo \"noMADE\" in doppia accezione italiana e inglese (nomade e non fatto/abbandonato).\r\n\r\n  ",
      "\r\n\r\n  Caratteristica del nomadismo ",
      " l'esistenza transitoria dell'individuo attraverso gli spazi ed i luoghi.\r\n\r\n  ",
      "\r\n\r\n  In questo senso, il contest si propone di esplorare il progetto di architettura attraverso i temi dell'effimero.",
      " ",
      " ",
      " un termine che si riferisce a qualcosa di appunto transitorio, passeggero o di breve durata.\r\n\r\n  ",
      "\r\n\r\n  L'effimerit",
      " pu",
      " essere associata a esperienze, oggetti o concetti che sono fugaci o temporanei, spesso caratterizzati dalla loro natura di passaggio e dalla loro tendenza a scomparire rapidamente, o ad essere dimenticati/ricordati nel tempo.\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      " Il concorso ",
      " ",
      " gli studenti e a tutti gli appassionati di architettura, designer, artisti e creativi in generale.",
      "\r\n\r\n  ",
      " ",
      " specifica ma solo passione e curiosit",
      ".",
      "\r\n\r\n  ",
      " Si pu",
      " partecipare ",
      " (",
      " membri per team).\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      " Ticket full pass 4 giorni Red Valley",
      "\r\n\r\n  ",
      " Buono tatuaggi di ",
      "100 presso Baldufura",
      "\r\n\r\n  ",
      " Buono dal valore di ",
      "50 per la libreria Il Labirinto",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  Deadline: ",
      "",
      "\r\n\r\n  Indirizzo email: ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  ",
      "\r\n\r\n  "
    ], [
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "IL TEMA"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "tema"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "\"Effimero\""
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "ò"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "A CHI E' RIVOLTO?"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "aperto a tutti"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: Utils.escaper([
                "Non ",
                " richiesta alcuna qualifica"
              ], ["è"])
        }
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "ò"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "individualmente o in team"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "massimo 2"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "PREMI"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "1#"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "2#"
        }
      },
      {
        TAG: "Str",
        _0: "€"
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "3#"
        }
      },
      {
        TAG: "Str",
        _0: "€"
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "+ 1 Menzione d'onore"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "INFO PER LA CONSEGNA"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "2 GIUGNO ORE 23:59"
        }
      },
      "NL",
      {
        TAG: "Link",
        _0: "mailto:asap.arkimastria@yahoo.it",
        _1: {
          TAG: "Strong",
          _0: {
            TAG: "Str",
            _0: "asap.arkimastria@yahoo.it"
          }
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "SCARICA IL BANDO ORA !!!"
        }
      },
      "NL"
    ]);

function $$default() {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "GDC9.0 AI Contest",
                      description: "Arkimastria, in occasione della Giornata del Colore 9.0, lancia la seconda edizione del Arkificial Intelligence Contest, un concorso di idee per l'architettura, realizzate attraverso l'uso dei software di intelligenza artificiale generativa.",
                      ogImage: "/static/img/gdc/GDC9.0_AI_Contest_Cover.webp"
                    }, "meta"),
                JsxRuntime.jsx(ArticleHeader.make, {
                      title: "AI CONTEST",
                      subtitle: "Architettura EFFIMERA",
                      image: "/static/img/gdc/GDC9.0_AI_Contest_Cover.webp",
                      eventType: "Contest"
                    }, "header"),
                JsxRuntime.jsx("div", {
                      children: contents,
                      className: "p-4"
                    }, "content"),
                JsxRuntime.jsx(FloatBox.make, {
                      title: "Scarica il bando",
                      description: "Contiene tutte le informazioni per partecipare, scadenze e regole",
                      href: "https://drive.google.com/uc?export=download&id=1qbZkm9eHW9Zm375G69Kj4KW9Hx9u-JPr",
                      boxType: "Download"
                    }, "downloadbox")
              ]
            });
}

export {
  $$default as default,
}
/* contents Not a pure module */
