// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../../components/Meta.res.mjs";
import * as FloatBox from "../../../components/FloatBox.res.mjs";
import * as Template from "../../../utils/Template.res.mjs";
import * as ArticleHeader from "../../../components/ArticleHeader.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var contents = Template.template([
      "\r\n  Arkimastria, in occasione della Giornata del Colore 9.0, lancia il primo Contest dedicato alla progettazione di un elemento d'arredo in collaborazione con Diego Moretti di ",
      ", una affermata realt",
      " attiva da tre generazioni in continua evoluzione, da sempre impegnata nella promozione dell'artigianalit",
      ". L'oggetto del contest ",
      " uno sgabello, che incarna l'anima nomade dell'evento, semplice da costruire e da trasportare\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  Il ",
      " scelto per la GDC di quest'anno ",
      " riassunto nel titolo \"",
      "\" in doppia accezione italiana e inglese (nomade e non fatto/abbandonato). Caratteristica del nomadismo ",
      " l'esistenza transitoria dell'individuo attraverso gli spazi ed i luoghi.\r\n  ",
      "\r\n  ",
      "\r\n  In questo senso, il contest si propone di esplorare il progetto architettonico attraverso un arredo che ridisegna e colonizza lo spazio. Un oggetto versatile, che ti accompagna nel viaggio e ti permette di abitare gli spazi anche se in maniera temporanea. Abitare, in una prospettiva nomade, significa caratterizzare un luogo per un tempo limitato e modificarne il paesaggio, sentirlo proprio, viverlo con i propri modi e le proprie abitudini. In quest'ottica, si sviluppa un senso di appartenenza al luogo che contribuisce ad esprimerne e realizzarne il potenziale. La comunit",
      " studentesca non ",
      " nomade nel senso letterale del termine, ma ",
      " pi",
      " un gruppo eterogeneo di individui che compie una parte del proprio percorso insieme.\r\n  ",
      "\r\n  Una comunit",
      " transitoria che con il proprio passaggio modifica le caratteristiche spaziali e percettive dei luoghi che abita. \r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      " Il concorso ",
      " aperto a tutti gli studenti e a tutti gli appassionati di architettura, designer, pianificatori, paesaggisti, artisti e creativi in generale.",
      "\r\n  ",
      " Non ",
      " richiesta alcuna qualifica specifica ma solo passione e curiosit",
      ".",
      "\r\n  ",
      " Le proposte di progettazione possono essere sviluppate individualmente o in team (massimo 2 membri).\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "",
      "\r\n  Supporto nella realizzazione di una linea di tre arredi (sgabello, sedia e tavolo) in armonia con il tema e nel rispetto delle linee guida del contest \"Spartano\" nel laboratorio di Ebanisteria Meccanica.",
      "",
      "\r\n  ",
      "",
      "\r\n  Set professionale di matite e chine per tradurre le tue idee in progetti, seguendo il principio di Gregotti che vede il disegno come strumento essenziale per il processo di progettazione.",
      "",
      "\r\n  ",
      "",
      "\r\n  \"Autoprogettazione\" di Enzo Mari, un libro fondamentale che promuove il concetto di fare da s",
      " nel design, fornendo le basi per la riscoperta delle proprie capacit",
      " creative e manuali.",
      "",
      "\r\n  ",
      "",
      "",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  Deadline: ",
      "",
      "\r\n  Indirizzo email: ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  "
    ], [
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "Ebanisteria Meccanica"
        }
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "IL TEMA"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "tema"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "noMADE"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      "NL",
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "ù"
      },
      "NL",
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "A CHI E' RIVOLTO?"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "PREMI"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "1° CLASSIFICATO:"
        }
      },
      "NL",
      "NL",
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "2° CLASSIFICATO:"
        }
      },
      "NL",
      "NL",
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "3° CLASSIFICATO:"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "é"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "+ 1 Menzione d'onore"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "Tutti e 4 i vincitori potranno realizzare il proprio progetto dal vivo durante il workshop di Ebanisteria meccanica per la GDC9.0 il 10/06 presso la sede di Arkimastria."
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "INFO PER LA CONSEGNA"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "30 MAGGIO ORE 23:59"
        }
      },
      "NL",
      {
        TAG: "Link",
        _0: "mailto:asap.arkimastria@yahoo.it",
        _1: {
          TAG: "Strong",
          _0: {
            TAG: "Str",
            _0: "asap.arkimastria@yahoo.it"
          }
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "SCARICA IL BANDO ORA !!!"
        }
      }
    ]);

function $$default() {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "GDC9.0 Design Spartano Contest",
                      description: "Arkimastria, in occasione della Giornata del Colore 9.0, lancia il primo Contest dedicato alla progettazione di un elemento d'arredo in collaborazione con Ebanisteria Meccanica, una affermata realtà attiva da tre generazioni in continua evoluzione, da sempre impegnata nella promozione dell'artigianalità.",
                      ogImage: "/static/img/gdc/GDC9.0_DS_Contest_Cover.webp"
                    }, "meta"),
                JsxRuntime.jsx(ArticleHeader.make, {
                      title: "Design Spartano Contest",
                      subtitle: "Una tavola, Uno sgabello",
                      image: "/static/img/gdc/GDC9.0_DS_Contest_Cover.webp",
                      eventType: "Contest"
                    }, "header"),
                JsxRuntime.jsx("div", {
                      children: contents,
                      className: "p-4"
                    }, "content"),
                JsxRuntime.jsx(FloatBox.make, {
                      title: "Scarica il bando",
                      description: "Contiene tutte le informazioni per partecipare, scadenze e regole",
                      href: "https://drive.google.com/uc?export=download&id=1aE_6yhInGurtrEYovsQKQZbRRPADClU8",
                      boxType: "Download"
                    }, "downloadbox")
              ]
            });
}

export {
  $$default as default,
}
/* contents Not a pure module */
