// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../components/Meta.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Index$Shared(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: props.title
                    }),
                JsxRuntime.jsx("h2", {
                      children: props.description
                    }),
                JsxRuntime.jsx("div", {
                      className: "h-20"
                    }),
                JsxRuntime.jsx("a", {
                      children: JsxRuntime.jsx("h2", {
                            children: "Clicca qui per tornare alla pagina della GDC 2024!"
                          }),
                      className: "link",
                      href: "/gdc"
                    })
              ],
              className: "w-full px-8 py-16 flex flex-col justify-center items-start"
            });
}

var Shared = {
  make: Index$Shared
};

function $$default() {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "Arkimastria",
                      description: "Homepage del sito ufficiale di Arkimastria a.s.a.p.d!"
                    }),
                JsxRuntime.jsx(Index$Shared, {
                      title: "Niente da vedere!!",
                      description: "C'è ancora un sacco di lavoro da fare, ancora qui è vuoto!"
                    })
              ]
            });
}

export {
  Shared ,
  $$default as default,
}
/* Meta Not a pure module */
