// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../components/Meta.res.mjs";
import * as Index from "./Index.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function NotFound$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "Errore 404",
                      description: "Non esiste alcuna pagina a questo indirizzo!"
                    }),
                JsxRuntime.jsx(Index.Shared.make, {
                      title: "Errore 404",
                      description: "Non esiste alcuna pagina a questo indirizzo!"
                    })
              ]
            });
}

var $$default = NotFound$default;

export {
  $$default as default,
}
/* Meta Not a pure module */
