// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../../components/Meta.res.mjs";
import * as Template from "../../../utils/Template.res.mjs";
import * as ArticleHeader from "../../../components/ArticleHeader.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var contents = Template.template([
      "\r\n    ",
      "\r\n    Un luogo e momento per la popolazione studentesca; la volont",
      " di dare l'occasione alla comunit",
      " universitaria di ricomporsi; avere la possibilit",
      " di usufruire degli spazi didattici come dei nuovi luoghi aperti al divertimento e alla spensieratezza di una serata trascorsa a guardare e commentare un film tra amici, oltre che colleghi. Cinemastria ",
      " tutto questo, il prodotto di Arkimastria nella ricerca di unione e divertimento per gli studenti.\r\n    ",
      "\r\n    ",
      "\r\n    ",
      "\r\n    Le pellicole sono un enorme concentrato di tecnica e presentano un'importante trasversalit",
      " tra le discipline che abbracciano la rappresentazione, modellazione, animazione, composizione musicale e disegno dello spazio. Non solo i film sono un ottimo modo per apprendere dettagli riguardo il mondo della progettazione e rappresentazione, sono anche un veicolo culturale alla portata di chiunque, capaci di legare competenze e gesti tecnici alla sceneggiatura che coinvolge lo spettatore a livello emotivo. Arkimastria sceglie anche i film come mezzo di apprendimento, oltre che svago e divertimento per gli studenti. \r\n    "
    ], [
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "PERCHE' CINEMASTRIA?"
        }
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "PERCHE' I FILM?"
        }
      },
      {
        TAG: "Str",
        _0: "à"
      }
    ]);

function CineIndex$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "GDC9.0 Cinemastria",
                      description: "Scopri le proiezioni cinematografiche targate GDC",
                      ogImage: "/static/img/gdc/GDC9.0_TitleCard.webp"
                    }),
                JsxRuntime.jsx(ArticleHeader.make, {
                      title: "CINEMASTRIA",
                      subtitle: "Le proiezioni di Arkimastria, targate GDC",
                      image: "/static/img/gdc/GDC9.0_Cinemastria1.webp",
                      eventType: "Cinema"
                    }),
                JsxRuntime.jsx("div", {
                      children: contents,
                      className: "p-4"
                    }, "content")
              ]
            });
}

var $$default = CineIndex$default;

export {
  $$default as default,
}
/* contents Not a pure module */
