// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventInfo from "../utils/EventInfo.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ArticleHeader(props) {
  var subtitle = props.subtitle;
  var match = EventInfo.getEventImage(props.eventType);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: props.title,
                              className: "w-4/5"
                            }),
                        subtitle !== undefined ? JsxRuntime.jsx("h2", {
                                children: subtitle,
                                className: "w-4/5"
                              }) : JsxRuntime.jsx(JsxRuntime.Fragment, {})
                      ],
                      className: "w-full px-4 py-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("img", {
                                    className: "icon w-4/5 h-4/5",
                                    alt: match[1],
                                    src: "/static/img/" + match[0]
                                  }),
                              className: "bg-background absolute top-0 right-0 w-1/4 aspect-square -translate-y-2/4 flex justify-center items-center rounded-full"
                            }),
                        JsxRuntime.jsx("img", {
                              className: "w-full h-full object-cover aspect-[3/2]",
                              src: props.image
                            })
                      ],
                      className: "relative"
                    })
              ]
            });
}

var make = ArticleHeader;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
