// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__List from "@rescript/core/src/Core__List.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function BreadcrumbBar(props) {
  return JsxRuntime.jsx("div", {
              children: Core__List.toArray(Core__List.map(props.path, (function (v) {
                          return JsxRuntime.jsx("a", {
                                      children: v,
                                      href: "/" + v
                                    });
                        }))),
              className: "flex flex-row gap-2"
            });
}

var make = BreadcrumbBar;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
