// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function InfoBox$MarqueeGradient(props) {
  var __direction = props.direction;
  var direction = __direction !== undefined ? __direction : "Forward";
  direction === "Forward";
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("img", {
                    className: "h-4 w-[672px] top-0 left-0 object-cover",
                    src: "/static/img/gdc-band.svg"
                  }),
              className: "w-2xl relative h-4 whitespace-nowrap overflow-hidden"
            });
}

function InfoBox$InfoRow(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("strong", {
                      children: props.title.toUpperCase() + ":"
                    }),
                JsxRuntime.jsx("p", {
                      children: props.children
                    })
              ],
              className: "flex flex-row gap-2 items-baseline"
            });
}

var InfoRow = {
  make: InfoBox$InfoRow
};

function InfoBox(props) {
  var title = props.title;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(InfoBox$MarqueeGradient, {}),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: title !== undefined ? title : "TOO LONG, WON'T READ"
                            }),
                        JsxRuntime.jsx("div", {
                              children: props.children,
                              className: "flex flex-col"
                            })
                      ],
                      className: "p-6 text-white flex flex-col gap-4"
                    }),
                JsxRuntime.jsx(InfoBox$MarqueeGradient, {
                      direction: "Reverse"
                    })
              ],
              className: "bg-black"
            });
}

var make = InfoBox;

export {
  InfoRow ,
  make ,
}
/* react/jsx-runtime Not a pure module */
