// Generated by ReScript, PLEASE EDIT WITH CARE

import Head from "next/head";
import * as JsxRuntime from "react/jsx-runtime";

function Meta(props) {
  var ogImage = props.ogImage;
  var ogTitle = props.ogTitle;
  var __ogDescription = props.ogDescription;
  var ogSiteName = props.ogSiteName;
  var __ogLocale = props.ogLocale;
  var title = props.title;
  var canonical = props.canonical;
  var description = props.description;
  var __keywords = props.keywords;
  var siteName = props.siteName;
  var keywords = __keywords !== undefined ? __keywords : [];
  var ogLocale = __ogLocale !== undefined ? __ogLocale : "it_IT";
  var ogDescription = __ogDescription !== undefined ? __ogDescription : description;
  var title$1 = title !== undefined && title !== "" ? title : siteName;
  var ogSiteName$1 = ogSiteName !== undefined ? ogSiteName : siteName;
  var ogTitle$1 = ogTitle !== undefined ? ogTitle : title$1;
  return JsxRuntime.jsxs(Head, {
              children: [
                JsxRuntime.jsx("title", {
                      children: title$1
                    }, "title"),
                JsxRuntime.jsx("meta", {
                      charSet: "utf-8"
                    }),
                JsxRuntime.jsx("meta", {
                      content: "width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, minimal-ui",
                      name: "viewport"
                    }),
                JsxRuntime.jsx("meta", {
                      content: description,
                      name: "description"
                    }, "description"),
                JsxRuntime.jsx("meta", {
                      content: keywords.join(","),
                      name: "keywords"
                    }, "keywords"),
                canonical !== undefined ? JsxRuntime.jsx("link", {
                        href: canonical,
                        rel: "canonical"
                      }, "canonical") : null,
                JsxRuntime.jsx("link", {
                      href: "/static/favicon/favicon.ico",
                      rel: "icon",
                      sizes: "any"
                    }),
                JsxRuntime.jsx("link", {
                      href: "/static/favicon/favicon.svg",
                      rel: "icon",
                      type: "image/svg.xml"
                    }),
                JsxRuntime.jsx("link", {
                      href: "/static/favicon/favicon.png",
                      rel: "apple-touch-icon"
                    }),
                JsxRuntime.jsx("meta", {
                      content: ogSiteName$1,
                      property: "og:site_name"
                    }, "og:site_name"),
                JsxRuntime.jsx("meta", {
                      content: ogLocale,
                      property: "og:locale"
                    }, "og:locale"),
                JsxRuntime.jsx("meta", {
                      content: ogTitle$1,
                      property: "og:title"
                    }, "og:title"),
                JsxRuntime.jsx("meta", {
                      content: ogDescription,
                      property: "og:description"
                    }, "og:description"),
                ogImage !== undefined ? JsxRuntime.jsx("meta", {
                        content: ogImage,
                        property: "og:image"
                      }, "og:image") : null,
                JsxRuntime.jsx("meta", {
                      content: title$1,
                      name: "twitter:title"
                    }, "twitter:title"),
                JsxRuntime.jsx("meta", {
                      content: description,
                      name: "twitter:description"
                    }, "twitter:description"),
                JsxRuntime.jsx("meta", {
                      content: "@reasonml",
                      name: "twitter:site"
                    }, "twitter:site"),
                JsxRuntime.jsx("meta", {
                      content: "@ReasonAssoc",
                      name: "twitter:creator"
                    }, "twitter:creator"),
                JsxRuntime.jsx("meta", {
                      content: "image/webp",
                      property: "og:image:type"
                    }),
                JsxRuntime.jsx("meta", {
                      content: "summary_large_image",
                      name: "twitter:card"
                    }, "twitter:card")
              ]
            });
}

var make = Meta;

export {
  make ,
}
/* next/head Not a pure module */
