// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function Navbar$Navlink(props) {
  var href = props.href;
  var sizeClass = props.sizeClass;
  var alt = props.alt;
  var icon = props.icon;
  if (href !== undefined) {
    return JsxRuntime.jsx(Link, {
                href: href,
                children: JsxRuntime.jsx("img", {
                      className: "icon " + sizeClass,
                      alt: alt,
                      src: icon
                    })
              });
  } else {
    return JsxRuntime.jsx("img", {
                className: "icon " + sizeClass,
                alt: alt,
                src: icon
              });
  }
}

function Navbar(props) {
  var path = props.path;
  var match = path && path.hd === "gdc" ? [
      true,
      path.tl ? false : true
    ] : [
      false,
      false
    ];
  var match$1 = match[0] ? [
      JsxRuntime.jsx(Navbar$Navlink, {
            icon: "/static/img/gdc.svg",
            alt: "GDC9.0 LOGO",
            sizeClass: "h-12",
            href: "/gdc"
          }),
      JsxRuntime.jsx(Navbar$Navlink, {
            icon: "/static/img/2024.svg",
            alt: "GDC9.0 2024 LOGOTYPE",
            sizeClass: "h-8"
          })
    ] : [
      JsxRuntime.jsx(Navbar$Navlink, {
            icon: "/static/img/arki-text.svg",
            alt: "Arkimastria Logotype",
            sizeClass: "h-6",
            href: "/"
          }),
      JsxRuntime.jsx(Navbar$Navlink, {
            icon: "/static/img/arki.svg",
            alt: "Arkimastria Logo",
            sizeClass: "h-10"
          })
    ];
  return JsxRuntime.jsxs("nav", {
              children: [
                match[1] ? JsxRuntime.jsx("img", {
                        className: "-z-10 absolute top-0 bottom-0 w-full h-full object-cover",
                        src: "/static/img/gdc-navbar-strip.webp"
                      }) : JsxRuntime.jsx("div", {}),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Navbar$Navlink, {
                                      icon: "/static/img/arki.svg",
                                      alt: "Arkimastria Logo",
                                      sizeClass: "h-10"
                                    }),
                                match$1[1]
                              ],
                              className: "flex justify-between h-full px-4 items-center"
                            }),
                        JsxRuntime.jsx("div", {
                              children: match$1[0],
                              className: "absolute top-0 flex justify-center w-full h-full items-center"
                            })
                      ],
                      className: "max-w-2xl m-auto relative h-full"
                    })
              ],
              className: "sticky top-0 z-50 h-16 bg-background"
            });
}

var make = Navbar;

export {
  make ,
}
/* next/link Not a pure module */
