// Generated by ReScript, PLEASE EDIT WITH CARE


function getEventImage($$event) {
  switch ($$event) {
    case "Party" :
        return [
                "party.svg",
                "Festa"
              ];
    case "Conference" :
        return [
                "conference.svg",
                "Conferenza"
              ];
    case "Cinema" :
        return [
                "cinema.svg",
                "Cinemastria"
              ];
    case "Workshop" :
        return [
                "workshop.svg",
                "Workshop"
              ];
    case "Contest" :
        return [
                "contest.svg",
                "Contest"
              ];
    
  }
}

export {
  getEventImage ,
}
/* No side effect */
