// Generated by ReScript, PLEASE EDIT WITH CARE


function getClassForTheme(theme) {
  switch (theme) {
    case "Blank" :
        return "";
    case "Orange" :
        return "gdc-orange";
    case "Pink" :
        return "gdc-pink";
    case "Cyan" :
        return "gdc-cyan";
    case "Yellow" :
        return "gdc-yellow";
    case "Special" :
        return "gdc-sp";
    
  }
}

export {
  getClassForTheme ,
}
/* No side effect */
