// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Core__List from "@rescript/core/src/Core__List.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function resolveTParam(tparam) {
  if (typeof tparam !== "object") {
    return JsxRuntime.jsx("br", {});
  }
  switch (tparam.TAG) {
    case "Strong" :
        return JsxRuntime.jsx("strong", {
                    children: resolveTParam(tparam._0)
                  });
    case "Header" :
        return JsxRuntime.jsx("h3", {
                    children: resolveTParam(tparam._0)
                  });
    case "Link" :
        return JsxRuntime.jsx("a", {
                    children: resolveTParam(tparam._1),
                    className: "link",
                    href: tparam._0
                  });
    case "Str" :
        return tparam._0;
    
  }
}

function template(strings, parameters) {
  if (strings.length === 0) {
    return [];
  }
  var items = {
    hd: strings[0],
    tl: /* [] */0
  };
  for(var i = 1 ,i_finish = strings.length; i <= i_finish; ++i){
    var s = strings[i];
    var p = parameters[i - 1 | 0];
    items = Belt_List.concatMany([
          items,
          {
            hd: resolveTParam(p),
            tl: {
              hd: s,
              tl: /* [] */0
            }
          }
        ]);
  }
  return Core__List.toArray(items);
}

export {
  template ,
}
/* react/jsx-runtime Not a pure module */
