// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function splitPath(path) {
  var path$1 = path.startsWith("/") ? path.substring(1, path.length) : path;
  if (path$1 === "") {
    return [];
  } else {
    return path$1.split("/");
  }
}

function escaper(strings, parameters) {
  return Core__Array.reduceWithIndex(parameters, strings[0], (function (acc, p, i) {
                var str = strings[i + 1 | 0];
                return acc + p + str;
              }));
}

function conditionalWrapper(wrapper, children) {
  return wrapper(children);
}

export {
  splitPath ,
  escaper ,
  conditionalWrapper ,
}
/* No side effect */
