// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../../components/Meta.res.mjs";
import * as InfoBox from "../../../components/InfoBox.res.mjs";
import * as Template from "../../../utils/Template.res.mjs";
import * as ArticleHeader from "../../../components/ArticleHeader.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var contents = Template.template([
      "\r\n  BlueFriday ",
      " il secondo workshop organizzato da Arkimastria in occasione della GDC9.0. Tenuto da Ginkgomag, ti insegner",
      " ad utilizzare la tecnica della cianotipia per produrre stampe di alta qualit",
      ".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  La cianotipia ",
      " una tecnica fotografica alternativa, sviluppata nel XIX secolo, che utilizza una soluzione fotosensibile a base di ferro e acqua per creare immagini di un blu intenso su supporti come carta o tessuto.",
      "\r\n  In questo workshop, esploreremo i fondamenti di questa affascinante tecnica artistica, aprendo le porte alla vostra creativit",
      ".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      " Introduzione alla storia e alla tecnica della cianotipia.",
      "\r\n  ",
      " Applicazione su supporti forniti o personali",
      "\r\n  ",
      " Utilizzo di oggetti tridimensionali e/o negativi fotografici per ottenere stampe uniche.",
      "\r\n  ",
      " Esposizione e sviluppo delle stampe cianotipiche.\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  Ginkgo ",
      " un collettivo interdisciplinare nato a Pistoia nel 2022 con lo scopo di creare nuovi spazi di connessione e dialogo e nuove modalit",
      " di fruizione degli spazi gi",
      " esistenti.",
      "\r\n  Il primo progetto curato dal collettivo ",
      " Ginkgomag, uno spazio editoriale aperto che affronta trimestralmente il tema della rigenerazione approcciandolo da un diverso punto di osservazione per ogni uscita.",
      "\r\n  Inoltre, il gruppo cura e promuove progetti editoriali e iniziative artistiche e culturali. \r\n  "
    ], [
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "COS'E' LA CIANOTIPIA?"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "COSA IMPARERAI:"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "POWERED BY"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      {
        TAG: "Str",
        _0: "è"
      },
      "NL"
    ]);

function BlueFriday$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "GDC9.0 BlueFriday",
                      description: "Arkimastria, in occasione della Giornata del Colore 9.0, lancia la seconda edizione del Arkificial Intelligence Contest, un concorso di idee per l'architettura, realizzate attraverso l'uso dei software di intelligenza artificiale generativa.",
                      ogImage: "/static/img/gdc/GDC9.0_BlueFriday_Cover.webp"
                    }, "meta"),
                JsxRuntime.jsx(ArticleHeader.make, {
                      title: "BlueFriday",
                      subtitle: "Workshop Cianotipia",
                      image: "/static/img/gdc/GDC9.0_BlueFriday_Cover.webp",
                      eventType: "Workshop"
                    }, "header"),
                JsxRuntime.jsx("div", {
                      className: "h-4"
                    }),
                JsxRuntime.jsxs(InfoBox.make, {
                      children: [
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Data",
                              children: "14 Giugno 2024, Venerdì"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Ora",
                              children: "Dalle 15:30 alle 18:00"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Luogo",
                              children: "Giardino Asilo Sella, Via Giuseppe Garibaldi 35"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "N. Partecipanti",
                              children: "15"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Organizzatore",
                              children: "Ginkgo"
                            })
                      ]
                    }),
                JsxRuntime.jsx("div", {
                      children: contents,
                      className: "p-4"
                    }, "content")
              ]
            });
}

var $$default = BlueFriday$default;

export {
  $$default as default,
}
/* contents Not a pure module */
