// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../../components/Meta.res.mjs";
import * as InfoBox from "../../../components/InfoBox.res.mjs";
import * as FloatBox from "../../../components/FloatBox.res.mjs";
import * as Template from "../../../utils/Template.res.mjs";
import * as ArticleHeader from "../../../components/ArticleHeader.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var contents = Template.template([
      "\r\n  BlueFriday ",
      " il terzo workshop organizzato da Arkimastria in occasione della GDC9.0. Tenuto da Ginkgomag, ti insegner",
      " ad utilizzare la tecnica della cianotipia per produrre stampe di alta qualit",
      ".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  La cianotipia ",
      " una tecnica fotografica alternativa, sviluppata nel XIX secolo, che utilizza una soluzione fotosensibile a base di ferro e acqua per creare immagini di un blu intenso su supporti come carta o tessuto.",
      "\r\n  In questo workshop, esploreremo i fondamenti di questa affascinante tecnica artistica, aprendo le porte alla vostra creativit",
      ".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      " Introduzione alla storia e alla tecnica della cianotipia.",
      "\r\n  ",
      " Applicazione su supporti forniti o personali",
      "\r\n  ",
      " Utilizzo di oggetti tridimensionali e/o negativi fotografici per ottenere stampe uniche.",
      "\r\n  ",
      " Esposizione e sviluppo delle stampe cianotipiche.\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      " Il numero massimo di partecipanti ",
      " limitato a ",
      " per garantire un'esperienza interattiva e personalizzata.",
      "\r\n  ",
      " L'evento ",
      " ",
      ", ",
      " comunque possibile fare una offerta libera e consapevole.",
      "\r\n  ",
      " ",
      " possibile iscriversi inviando ",
      " della page Instagram, oppure presso la nostra sede, piano terra del complesso Santa Chiara.",
      "\r\n  ",
      " Siete incoraggiati a ",
      ", come fiori, chiavi, giocattoli, o qualsiasi altra cosa abbia uno spessore. ",
      ": forniremo tutto il necessario per creare le vostre stampe uniche. ",
      "\r\n  ",
      " Il workshop si terr",
      " dalle ",
      " alle ",
      " nel giardino dell'Asilo Sella, ",
      ".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  Ginkgo ",
      " un collettivo interdisciplinare nato a Pistoia nel 2022 con lo scopo di creare nuovi spazi di connessione e dialogo e nuove modalit",
      " di fruizione degli spazi gi",
      " esistenti.",
      "\r\n  Il primo progetto curato dal collettivo ",
      " Ginkgomag, uno spazio editoriale aperto che affronta trimestralmente il tema della rigenerazione approcciandolo da un diverso punto di osservazione per ogni uscita.",
      "\r\n  Inoltre, il gruppo cura e promuove progetti editoriali e iniziative artistiche e culturali.\r\n  "
    ], [
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "COS'E' LA CIANOTIPIA?"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "COSA IMPARERAI:"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "UN PAIO DI INFO"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "15 persone"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "gratuito"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "È"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "\"BlueFriday\" nei DM"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "portare con voi oggetti di vario genere da cianotipare"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "Se non avete nulla da portare, non preoccupatevi"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "15:30"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "18:00"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "Via Giuseppe Garibaldi 35 Alghero"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "POWERED BY"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      {
        TAG: "Str",
        _0: "è"
      },
      "NL"
    ]);

function BlueFriday$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "GDC9.0 BlueFriday",
                      description: "BlueFriday è il terzo workshop organizzato da Arkimastria in occasione della GDC9.0. Tenuto da Ginkgomag, ti insegnerà ad utilizzare la tecnica della cianotipia per produrre stampe di alta qualità.",
                      ogImage: "/static/img/gdc/GDC9.0_BlueFriday_Cover.webp"
                    }, "meta"),
                JsxRuntime.jsx(ArticleHeader.make, {
                      title: "BlueFriday",
                      subtitle: "Workshop Cianotipia",
                      image: "/static/img/gdc/GDC9.0_BlueFriday_Cover.webp",
                      eventType: "Workshop"
                    }, "header"),
                JsxRuntime.jsxs(InfoBox.make, {
                      children: [
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Data",
                              children: "14 Giugno 2024, Venerdì"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Ora",
                              children: "Dalle 15:30 alle 18:00"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Luogo",
                              children: "Giardino Asilo Sella, Via Giuseppe Garibaldi 35"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "N. Partecipanti",
                              children: "15"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Organizzatore",
                              children: "Ginkgo"
                            })
                      ]
                    }),
                JsxRuntime.jsx("div", {
                      className: "h-8"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            className: "w-full max-w-sm h-full",
                            alt: "Logo Ginkgomag",
                            src: "/static/img/ginkgomag.svg"
                          }),
                      className: "flex justify-center items-center px-8"
                    }),
                JsxRuntime.jsx("div", {
                      children: contents,
                      className: "p-4 pt-8"
                    }, "content"),
                JsxRuntime.jsx(FloatBox.make, {
                      title: "Unisciti alla chat WhatsApp",
                      description: "Richiedi di entrare nella chat del workshop per prenotarti",
                      href: "https://chat.whatsapp.com/Hl1lQP97B6AKuAmTG9Unin",
                      boxType: "WhatsappChat"
                    }, "downloadbox")
              ]
            });
}

var $$default = BlueFriday$default;

export {
  $$default as default,
}
/* contents Not a pure module */
