// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../../components/Meta.res.mjs";
import * as InfoBox from "../../../components/InfoBox.res.mjs";
import * as FloatBox from "../../../components/FloatBox.res.mjs";
import * as Template from "../../../utils/Template.res.mjs";
import * as ArticleHeader from "../../../components/ArticleHeader.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var contents = Template.template([
      "\r\n  Il workshop Design Spartano offre un approccio utile a porre le basi fondamentali per iniziare ad immergersi nel mondo della lavorazione del legno.",
      "L'intero percorso del workshop sar",
      " guidato e supervisionato da Diego Moretti di Ebanisteria Meccanica. La parte teorica, incentrata sulla conoscenza della materia ",
      " seguita da una parte pratica: la realizzazione dello sgabello spartano.",
      "I vincitori, annunciati proprio nel giorno del Workshop, potranno invece realizzare il loro sgabello.\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      " Il numero massimo di partecipanti ",
      " limitato a ",
      " per garantire un'esperienza interattiva e personalizzata. Sono presenti anche 4 posti extra per i vincitori del ",
      ".",
      "\r\n  ",
      " L'evento ",
      " ",
      ", ",
      " comunque possibile fare una offerta libera e consapevole.",
      "\r\n  ",
      " ",
      " possibile iscriversi inviando ",
      " della page Instagram, oppure presso la nostra sede, piano terra del complesso Santa Chiara.",
      "\r\n  ",
      " Il workshop si terr",
      " dalle ",
      " alle ",
      " nello Student Hub di ",
      ".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  Ebanisteria Meccanica ",
      " un brand sardo basato sulla tradizione artigiana della lavorazione del legno, che progetta e realizza oggetti di design, arredo e utilit\xc3\xa0 ponendo cura nei dettagli, nelle materie prime e nel processo \"fatto a mano\".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "",
      "\r\n  ",
      ": Accoglienza e presentazione dei partecipanti",
      "\r\n  ",
      ": Presentazione di Diego Moretti, Ebanisteria Meccanica e introduzione al workshop",
      "\r\n  ",
      ": Tinteggiatura arredi",
      "\r\n  ",
      ": Pausa Pranzo - Asciugatura della tinteggiatura",
      "\r\n  ",
      "\r\n  ",
      "",
      "\r\n  ",
      ": Lezione sul legno, presentazione VINCITORE del contest \"SPARTANO\", presentazione dello sgabello di Ebanisteria Meccanica",
      "\r\n  ",
      ": Realizzazione e costruzione dello sgabello con la supervisione di Diego Moretti",
      "\r\n  ",
      "\r\n  ",
      "",
      "\r\n  ",
      ": Chiusura del workshop e saluti",
      "\r\n  ",
      ": Invito a tutti i partecipanti per un momento informale di socializzazione e celebrazione dell'evento con bevande e spuntini",
      "\r\n  "
    ], [
      "NL",
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "UN PAIO DI INFO"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "11 persone"
        }
      },
      {
        TAG: "Link",
        _0: "/gdc/contest/dscontest",
        _1: {
          TAG: "Str",
          _0: "Design Spartano Contest"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "gratuito"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "È"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "\"DesignSpartano\" nei DM"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "09:00"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "19:00"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "Piazza Santa Croce, Alghero"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "POWERED BY"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "IL PROGRAMMA"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "MATTINA - PARTE 1: Arkitchen & Print"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "9:00 - 9:30"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "9:30 - 10:15"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "10:30 - 13:00"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "13:00 - 15:00"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "POMERIGGIO - PARTE 2: Una tavola, Uno sgabello \"Spartano\""
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "15:00 - 16:30"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "16:30 - 19:00"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "SERA - PARTE 3: Finale + Evento sociale"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "19:00"
        }
      },
      "NL",
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "Dalle 19:00 in poi"
        }
      },
      "NL"
    ]);

function DSWorkshop$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "GDC9.0 Ebanisteria Meccanica",
                      description: "Il workshop Design Spartano offre un approccio utile a porre le basi fondamentali per iniziare ad immergersi nel mondo della lavorazione del legno.",
                      ogImage: "/static/img/gdc/GDC9.0_DSWorkshop_Cover.webp"
                    }, "meta"),
                JsxRuntime.jsx(ArticleHeader.make, {
                      title: "Ebanisteria Meccanica",
                      subtitle: "Free workshop Design Spartano",
                      image: "/static/img/gdc/GDC9.0_DSWorkshop_Cover.webp",
                      eventType: "Workshop"
                    }, "header"),
                JsxRuntime.jsxs(InfoBox.make, {
                      children: [
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Data",
                              children: "10 Giugno 2024, Lunedì"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Ora",
                              children: "Dalle 09:00 alle 19:00"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Luogo",
                              children: "Student Hub, Piazza Santa Croce AHO"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "N. Partecipanti",
                              children: "11 + 4 vincitori DS Contest"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Organizzatore",
                              children: "Ebanisteria Meccanica"
                            })
                      ]
                    }),
                JsxRuntime.jsx("div", {
                      className: "h-8"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("img", {
                            className: "w-full max-w-sm h-full",
                            alt: "Logo Ebanisteria Meccanica",
                            src: "/static/img/ebanisteria-meccanica.svg"
                          }),
                      className: "flex justify-center items-center px-8"
                    }),
                JsxRuntime.jsx("div", {
                      children: contents,
                      className: "p-4 pt-8"
                    }, "content"),
                JsxRuntime.jsx(FloatBox.make, {
                      title: "Unisciti alla chat WhatsApp",
                      description: "Richiedi di entrare nella chat del workshop per prenotarti",
                      href: "https://chat.whatsapp.com/Cci3RYr8QyxBKV0lFgHa36",
                      boxType: "WhatsappChat"
                    }, "downloadbox")
              ]
            });
}

var $$default = DSWorkshop$default;

export {
  $$default as default,
}
/* contents Not a pure module */
