// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../../../components/Meta.res.mjs";
import * as InfoBox from "../../../components/InfoBox.res.mjs";
import * as FloatBox from "../../../components/FloatBox.res.mjs";
import * as Template from "../../../utils/Template.res.mjs";
import * as ArticleHeader from "../../../components/ArticleHeader.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var contents = Template.template([
      "\r\n  Il secondo workshop organizzato da Arkimastria in occasione della GDC9.0 ",
      " dedicato alla linografia, una tecnica che permette di creare timbri che possono poi essere utilizzati per la stampa di disegni su vari superfici. Seguito da Caterina Pirisi, tattoo artist di Balduf",
      "ra, il workshop ti insegner",
      " le basi di questa antica tecnica.\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  Il Lino Cutting and Printing ",
      " una forma d'arte che combina la precisione del taglio del linoleum con la creativit",
      " della stampa.",
      "In questo evento, esploreremo le tecniche di incisione e stampa su linoleum, aprendo nuove possibilit",
      " espressive per gli artisti e gli appassionati di grafica. \r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      " Introduzione alla tecnica di taglio del linoleum e alle sue potenzialit\xc3\xa0 artistiche.",
      "\r\n  ",
      " Tecniche di incisione e preparazione del blocco di linoleum.",
      "\r\n  ",
      " Utilizzo degli strumenti di taglio per creare disegni e pattern.",
      "\r\n  ",
      " Stampa dei disegni incisi su carta.\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  ",
      " Il numero massimo di partecipanti ",
      " limitato a ",
      " per garantire un'esperienza interattiva e personalizzata.",
      "\r\n  ",
      " L'evento ",
      " ",
      ", ",
      " comunque possibile fare una offerta libera e consapevole.",
      "\r\n  ",
      " ",
      " possibile iscriversi inviando ",
      " della page Instagram, oppure presso la nostra sede, piano terra del complesso Santa Chiara.",
      "\r\n  ",
      " Il workshop si terr",
      " dalle ",
      " alle ",
      " nello Student Hub di ",
      ".\r\n  ",
      "\r\n  ",
      "\r\n  ",
      "\r\n  Caterina Pirisi nasce a Montecchio Emilia nel 1990. Nel 2017 si diploma in Grafica d'Arte e Progettazione all'Accademia di Belle Arti di Sassari e nel 2018 consegue il Master di I livello in Illustrazione editoriale alla scuola Ars in Fabula di Macerata.",
      "Nel 2021 comincia a tatuare, proseguendo il percorso artistico tra acquerelli, stampa artigianale su carta e stoffa, lavori in legno e Das e qualsiasi altra tecnica creativa +stuzzichi la sua fantasia.\r\n  "
    ], [
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "ù"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "COS'E' LA LINOGRAFIA?"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      {
        TAG: "Str",
        _0: "à"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "COSA IMPARERAI:"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "UN PAIO DI INFO"
        }
      },
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "12 persone"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "è"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "gratuito"
        }
      },
      {
        TAG: "Str",
        _0: "è"
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "È"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "\"Linografia\" nei DM"
        }
      },
      "NL",
      {
        TAG: "Str",
        _0: "•"
      },
      {
        TAG: "Str",
        _0: "à"
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "16:30"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "18:30"
        }
      },
      {
        TAG: "Strong",
        _0: {
          TAG: "Str",
          _0: "Piazza Santa Croce, Alghero"
        }
      },
      "NL",
      "NL",
      {
        TAG: "Header",
        _0: {
          TAG: "Str",
          _0: "POWERED BY"
        }
      },
      "NL"
    ]);

function LinoCutPrint$default(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Meta.make, {
                      siteName: "GDC9.0 Linografia",
                      description: "Il secondo workshop organizzato da Arkimastria in occasione della GDC9.0 è dedicato alla linografia, una tecnica che permette di creare timbri che possono poi essere utilizzati per la stampa di disegni su vari superfici. Seguito da Caterina Pirisi, tattoo artist di Baldufùra, il workshop ti insegnerà le basi di questa antica tecnica.",
                      ogImage: "/static/img/gdc/GDC9.0_LinoCutPrint_Cover.webp"
                    }, "meta"),
                JsxRuntime.jsx(ArticleHeader.make, {
                      title: "Linografia",
                      subtitle: "Free workshop",
                      image: "/static/img/gdc/GDC9.0_LinoCutPrint_Cover.webp",
                      eventType: "Workshop"
                    }, "header"),
                JsxRuntime.jsxs(InfoBox.make, {
                      children: [
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Data",
                              children: "12 Giugno 2024, Mercoledì"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Ora",
                              children: "Dalle 16:30 alle 18:30"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Luogo",
                              children: "Student Hub, Piazza Santa Croce AHO"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "N. Partecipanti",
                              children: "12"
                            }),
                        JsxRuntime.jsx(InfoBox.InfoRow.make, {
                              title: "Organizzatore",
                              children: "Caterina Pirisi"
                            })
                      ]
                    }),
                JsxRuntime.jsx("div", {
                      children: contents,
                      className: "p-4"
                    }, "content"),
                JsxRuntime.jsx(FloatBox.make, {
                      title: "Unisciti alla chat WhatsApp",
                      description: "Richiedi di entrare nella chat del workshop per prenotarti",
                      href: "https://chat.whatsapp.com/Hl1lQP97B6AKuAmTG9Unin",
                      boxType: "WhatsappChat"
                    }, "downloadbox")
              ]
            });
}

var $$default = LinoCutPrint$default;

export {
  $$default as default,
}
/* contents Not a pure module */
