// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./utils/Utils.res.mjs";
import * as React from "react";
import * as Core__List from "@rescript/core/src/Core__List.res.mjs";
import * as Router from "next/router";
import * as MobileLayout from "./layouts/MobileLayout.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function $$default(props) {
  var router = Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  var path = Core__List.fromArray(Utils.splitPath(router.asPath));
  var pageLayout;
  if (path && path.hd === "gdc") {
    var rest = path.tl;
    if (rest) {
      switch (rest.hd) {
        case "cinemastria" :
            pageLayout = rest.tl ? ({
                  TAG: "GDC",
                  _0: "Blank"
                }) : ({
                  TAG: "GDC",
                  _0: "Black"
                });
            break;
        case "contest" :
            var match = rest.tl;
            if (match) {
              switch (match.hd) {
                case "aicontest" :
                    pageLayout = match.tl ? ({
                          TAG: "GDC",
                          _0: "Blank"
                        }) : ({
                          TAG: "GDC",
                          _0: "Orange"
                        });
                    break;
                case "dscontest" :
                    pageLayout = match.tl ? ({
                          TAG: "GDC",
                          _0: "Blank"
                        }) : ({
                          TAG: "GDC",
                          _0: "Pink"
                        });
                    break;
                default:
                  pageLayout = {
                    TAG: "GDC",
                    _0: "Blank"
                  };
              }
            } else {
              pageLayout = {
                TAG: "GDC",
                _0: "Blank"
              };
            }
            break;
        case "workshop" :
            var match$1 = rest.tl;
            if (match$1) {
              switch (match$1.hd) {
                case "bluefriday" :
                    pageLayout = match$1.tl ? ({
                          TAG: "GDC",
                          _0: "Blank"
                        }) : ({
                          TAG: "GDC",
                          _0: "Cyan"
                        });
                    break;
                case "dsworkshop" :
                    pageLayout = match$1.tl ? ({
                          TAG: "GDC",
                          _0: "Blank"
                        }) : ({
                          TAG: "GDC",
                          _0: "Pink"
                        });
                    break;
                case "linocutprint" :
                    pageLayout = match$1.tl ? ({
                          TAG: "GDC",
                          _0: "Blank"
                        }) : ({
                          TAG: "GDC",
                          _0: "Yellow"
                        });
                    break;
                default:
                  pageLayout = {
                    TAG: "GDC",
                    _0: "Blank"
                  };
              }
            } else {
              pageLayout = {
                TAG: "GDC",
                _0: "Blank"
              };
            }
            break;
        default:
          pageLayout = {
            TAG: "GDC",
            _0: "Blank"
          };
      }
    } else {
      pageLayout = {
        TAG: "GDC",
        _0: "Special"
      };
    }
  } else {
    pageLayout = "Normal";
  }
  return JsxRuntime.jsx(MobileLayout.make, {
              path: path,
              pageLayout: pageLayout,
              children: content
            });
}

export {
  $$default as default,
}
/* react Not a pure module */
