// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Footer from "../components/Footer.res.mjs";
import * as Navbar from "../components/Navbar.res.mjs";
import * as GDCUtils from "../utils/GDCUtils.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function MobileLayout(props) {
  var pageLayout = props.pageLayout;
  var pageTheme;
  if (typeof pageLayout !== "object") {
    pageTheme = "";
  } else {
    var theme = pageLayout._0;
    pageTheme = theme === "Blank" ? "" : GDCUtils.getClassForTheme(theme);
  }
  var fontClass;
  fontClass = typeof pageLayout !== "object" ? "" : "gdc-type";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Navbar.make, {
                      path: props.path
                    }, "navbar"),
                JsxRuntime.jsx("div", {
                      children: props.children,
                      className: "min-h-screen max-w-2xl m-auto"
                    }, "content"),
                JsxRuntime.jsx(Footer.make, {}, "footer")
              ],
              className: "h-full bg-background text-foreground " + fontClass + " " + pageTheme
            }, "body");
}

var make = MobileLayout;

export {
  make ,
}
/* Footer Not a pure module */
